version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - host
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboard/fantom_overview.json:/var/lib/grafana/dashboards/fantom_overview.json

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - host
    volumes:
      - prometheus-volume:/prometheus

volumes:
  grafana-volume:
    external: true
  prometheus-volume:
    external: true
